onEvent('recipes', event => { 
    event.remove({ id: 'tac:craft_qbz_95' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qbz_95"},"materials":[{"item":"minecraft:iron_ingot","count":76},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_qbz_191' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qbz_191"},"materials":[{"item":"minecraft:iron_ingot","count":98},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_qsz92g1' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qsz92g1"},"materials":[{"item":"minecraft:iron_ingot","count":20},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_rpg7' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:rpg7"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":20}]})
    event.remove({ id: 'tac:craft_scar_h' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:scar_h"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_scar_l' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:scar_l"},"materials":[{"item":"minecraft:iron_ingot","count":70},{"item":"minecraft:diamond","count":2},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_sig_mcx_spear' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sig_mcx_spear"},"materials":[{"item":"minecraft:iron_ingot","count":92},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":18}]})
    event.remove({ id: 'tac:craft_sks_tactical' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sks_tactical"},"materials":[{"item":"minecraft:iron_ingot","count":66},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_sks' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sks"},"materials":[{"item":"minecraft:iron_ingot","count":20},{"item":"minecraft:spruce_log","count":8},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_smle_iii' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:smle_iii"},"materials":[{"item":"minecraft:iron_ingot","count":60},{"item":"minecraft:spruce_log","count":10},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_spas_12' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:spas_12"},"materials":[{"item":"minecraft:iron_ingot","count":60},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_springfield_1903' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:springfield_1903"},"materials":[{"item":"minecraft:iron_ingot","count":48},{"item":"minecraft:oak_log","count":14},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_sten_mk_ii_oss' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sten_mk_ii_oss"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_sten_mk_ii' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sten_mk_ii"},"materials":[{"item":"minecraft:iron_ingot","count":18},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_sti2011' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sti2011"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"minecraft:gold_ingot","count":16},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_type81_x' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:type81_x"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_vector45' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:vector45"},"materials":[{"item":"minecraft:iron_ingot","count":72},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_walther_ppk' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:walther_ppk"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_x95r' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:x95r"},"materials":[{"item":"minecraft:iron_ingot","count":84},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:m1928' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1928"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"minecraft:oak_log","count":4},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_vc61' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:vz61"},"materials":[{"item":"minecraft:iron_ingot","count":14},{"item":"minecraft:oak_log","count":4},{"item":"create:precision_mechanism","count":6}]})
})