onEvent('recipes', event => { 
    event.remove({ id: 'tac:craft_aa_12' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:aa_12"},"materials":[{"item":"minecraft:iron_ingot","count":96},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_ai_awp' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:ai_awp"},"materials":[{"item":"minecraft:iron_ingot","count":90},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":15}]})
    event.remove({ id: 'tac:craft_ak47' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:ak47"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"minecraft:acacia_log","count":4},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_ar10' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:ar_10"},"materials":[{"item":"minecraft:iron_ingot","count":110},{"item":"minecraft:diamond","count":2},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_ar15hm' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:ar_15_hellmouth"},"materials":[{"item":"minecraft:iron_ingot","count":35},{"item":"minecraft:diamond","count":1},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_c96' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:c96"},"materials":[{"item":"minecraft:iron_ingot","count":14},{"item":"minecraft:spruce_log","count":2},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_cz75_auto' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:cz75_auto"},"materials":[{"item":"minecraft:iron_ingot","count":36},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_cz75' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:cz75"},"materials":[{"item":"minecraft:iron_ingot","count":26},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_db_long' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:db_long"},"materials":[{"item":"minecraft:iron_ingot","count":16},{"item":"minecraft:oak_log","count":4},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_db_short' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:db_short"},"materials":[{"item":"minecraft:iron_ingot","count":8},{"item":"minecraft:oak_log","count":1},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_de_lisle' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:de_lisle"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"minecraft:spruce_log","count":6},{"item":"create:precision_mechanism","count":7}]})
    event.remove({ id: 'tac:craft_deagle_357' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:deagle_357"},"materials":[{"item":"minecraft:iron_ingot","count":72},{"item":"minecraft:diamond","count":2},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_dp28' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:dp28"},"materials":[{"item":"minecraft:iron_ingot","count":42},{"item":"minecraft:acacia_log","count":6},,{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_espadon' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:espadon"},"materials":[{"item":"minecraft:iron_ingot","count":110},{"item":"minecraft:diamond","count":2},{"item":"create:precision_mechanism","count":20}]})
    event.remove({ id: 'tac:craft_fn_fal' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:fn_fal"},"materials":[{"item":"minecraft:iron_ingot","count":122},{"item":"minecraft:spruce_log","count":10},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_fr_f2' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:fr_f2"},"materials":[{"item":"minecraft:iron_ingot","count":112},{"item":"minecraft:oak_log","count":24},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_glock_17' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:glock_17"},"materials":[{"item":"minecraft:iron_ingot","count":18},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_glock_18' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:glock_18"},"materials":[{"item":"minecraft:iron_ingot","count":32},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_hk_mp5a5' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:hk_mp5a5"},"materials":[{"item":"minecraft:iron_ingot","count":40},{"item":"create:precision_mechanism","count":6}]})
    event.remove({ id: 'tac:craft_hk416_a5' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:hk416_a5"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_kar98' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:kar98"},"materials":[{"item":"minecraft:iron_ingot","count":72},{"item":"minecraft:spruce_log","count":12},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_m1_garand' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1_garand"},"materials":[{"item":"minecraft:iron_ingot","count":84},{"item":"minecraft:spruce_log","count":12},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_m1a1_smg' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1a1_smg"},"materials":[{"item":"minecraft:iron_ingot","count":16},{"item":"minecraft:oak_log","count":3},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_m4' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m4"},"materials":[{"item":"minecraft:iron_ingot","count":62},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_m16a1' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m16a1"},"materials":[{"item":"minecraft:iron_ingot","count":34},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_m16a4' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m16a4"},"materials":[{"item":"minecraft:iron_ingot","count":66},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_m24' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m24"},"materials":[{"item":"minecraft:iron_ingot","count":106},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_m60' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m60"},"materials":[{"item":"minecraft:iron_ingot","count":74},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_m79' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m79"},"materials":[{"item":"minecraft:iron_ingot","count":25},{"item":"minecraft:spruce_log","count":6},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_m82a2' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m82a2"},"materials":[{"item":"minecraft:iron_block","count":16},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":18}]})
    event.remove({ id: 'tac:craft_m92fs' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m92fs"},"materials":[{"item":"minecraft:iron_ingot","count":24},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_m249' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m249"},"materials":[{"item":"minecraft:iron_ingot","count":96},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_m870_classic' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m870_classic"},"materials":[{"item":"minecraft:iron_ingot","count":36},{"item":"minecraft:oak_log","count":8},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_m1011' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1014"},"materials":[{"item":"minecraft:iron_ingot","count":80},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_m1873' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1873"},"materials":[{"item":"minecraft:iron_ingot","count":10},{"item":"create:precision_mechanism","count":7}]})
    event.remove({ id: 'tac:craft_m1894' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1894"},"materials":[{"item":"minecraft:iron_ingot","count":26},{"item":"minecraft:birch_log","count":2},{"item":"create:precision_mechanism","count":7}]})
    event.remove({ id: 'tac:craft_m1911' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1911"},"materials":[{"item":"minecraft:iron_ingot","count":26},{"item":"minecraft:oak_log","count":3},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_mg421' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mg42"},"materials":[{"item":"minecraft:iron_ingot","count":118},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_mgl_40mm' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mgl_40mm"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"minecraft:glass_pane","count":18},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":16}]})
    event.remove({ id: 'tac:craft_micro_uzi' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:micro_uzi"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_mk14' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mk14"},"materials":[{"item":"minecraft:iron_ingot","count":120},{"item":"create:precision_mechanism","count":13}]})
    event.remove({ id: 'tac:craft_mk23' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mk23"},"materials":[{"item":"minecraft:iron_ingot","count":42},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_mk47' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mk47"},"materials":[{"item":"minecraft:iron_ingot","count":82},{"item":"minecraft:diamond","count":6},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_mosberg590' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mosberg590"},"materials":[{"item":"minecraft:iron_ingot","count":48},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_mosin' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mosin"},"materials":[{"item":"minecraft:iron_ingot","count":40},{"item":"minecraft:acacia_log","count":10},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_mp7' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mp7"},"materials":[{"item":"minecraft:iron_ingot","count":66},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_mp9' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:mp9"},"materials":[{"item":"minecraft:iron_ingot","count":40},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_pkp_penchenberg' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:pkp_penchenberg"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_ppsh_41' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:ppsh_41"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"minecraft:spruce_log","count":6},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_qbz_95' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qbz_95"},"materials":[{"item":"minecraft:iron_ingot","count":76},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_qbz_191' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qbz_191"},"materials":[{"item":"minecraft:iron_ingot","count":98},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_qsz92g1' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:qsz92g1"},"materials":[{"item":"minecraft:iron_ingot","count":20},{"item":"create:precision_mechanism","count":5}]})
    event.remove({ id: 'tac:craft_rpg7' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:rpg7"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":20}]})
    event.remove({ id: 'tac:craft_scar_h' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:scar_h"},"materials":[{"item":"minecraft:iron_ingot","count":100},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":12}]})
    event.remove({ id: 'tac:craft_scar_l' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:scar_l"},"materials":[{"item":"minecraft:iron_ingot","count":70},{"item":"minecraft:diamond","count":2},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_sig_mcx_spear' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sig_mcx_spear"},"materials":[{"item":"minecraft:iron_ingot","count":92},{"item":"minecraft:diamond","count":4},{"item":"create:precision_mechanism","count":18}]})
    event.remove({ id: 'tac:craft_sks_tactical' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sks_tactical"},"materials":[{"item":"minecraft:iron_ingot","count":66},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_sks' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sks"},"materials":[{"item":"minecraft:iron_ingot","count":20},{"item":"minecraft:spruce_log","count":8},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_smle_iii' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:smle_iii"},"materials":[{"item":"minecraft:iron_ingot","count":60},{"item":"minecraft:spruce_log","count":10},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_spas_12' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:spas_12"},"materials":[{"item":"minecraft:iron_ingot","count":60},{"item":"create:precision_mechanism","count":11}]})
    event.remove({ id: 'tac:craft_springfield_1903' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:springfield_1903"},"materials":[{"item":"minecraft:iron_ingot","count":48},{"item":"minecraft:oak_log","count":14},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_sten_mk_ii_oss' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sten_mk_ii_oss"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_sten_mk_ii' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sten_mk_ii"},"materials":[{"item":"minecraft:iron_ingot","count":18},{"item":"create:precision_mechanism","count":8}]})
    event.remove({ id: 'tac:craft_sti2011' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:sti2011"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"minecraft:gold_ingot","count":16},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_type81_x' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:type81_x"},"materials":[{"item":"minecraft:iron_ingot","count":28},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_vector45' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:vector45"},"materials":[{"item":"minecraft:iron_ingot","count":72},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_walther_ppk' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:walther_ppk"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:craft_x95r' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:x95r"},"materials":[{"item":"minecraft:iron_ingot","count":84},{"item":"create:precision_mechanism","count":9}]})
    event.remove({ id: 'tac:m1928' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:m1928"},"materials":[{"item":"minecraft:iron_ingot","count":30},{"item":"minecraft:oak_log","count":4},{"item":"create:precision_mechanism","count":10}]})
    event.remove({ id: 'tac:craft_vc61' })
    event.custom({"type":"tac:workbench","result":{"item":"tac:vz61"},"materials":[{"item":"minecraft:iron_ingot","count":14},{"item":"minecraft:oak_log","count":4},{"item":"create:precision_mechanism","count":6}]})
})