onEvent('item.tags', event => {
    event.add('notreepunching:weak_saws', '#forge:tools/axes')

    event.add('forge:ingots', 'steampowered:steel_ingot')
    event.add('forge:ingots/steel', 'steampowered:steel_ingot')
    event.add('forge:plates/steel', 'steampowered:steel_sheet')
    event.add('forge:plates/bronze', 'steampowered:bronze_sheet')
    event.add('kubejs:piston', 'minecraft:piston')
    event.add('kubejs:piston', 'minecraft:sticky_piston')

    event.add('diet:proteins', 'gofish:soup_can_open')
    event.add('diet:vegetables', 'gofish:soup_can_open')
    event.add('diet:fruits', 'gofish:fruit_can_open')
    event.add('diet:sugars', 'gofish:fruit_can_open')
    event.add('diet:proteins', 'gofish:magic_soup_can_open')
    event.add('diet:vegetables', 'gofish:magic_soup_can_open')
    event.add('diet:fruits', 'gofish:magic_soup_can_open')
    event.add('diet:grains', 'gofish:magic_soup_can_open')
    event.add('diet:sugars', 'gofish:magic_soup_can_open')

    event.add('diet:grains', 'gofish:scoop_rice_with_sweet_wing')
    event.add('diet:proteins', 'gofish:scoop_rice_with_sweet_wing')
    event.add('diet:proteins', 'gofish:essence_of_fish')
    event.add('diet:grains', 'gofish:oil_cake')

    event.remove('forge:tools/knives', 'croptopia:knife')

    event.add('forge:meat_cooked', 'croptopia:cooked_anchovy')
    event.add('forge:meat_cooked', 'croptopia:cooked_shrimp')
    event.add('forge:meat_cooked', 'croptopia:cooked_tuna')

    event.add('kubejs:banned_tools', 'minecraft:wooden_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:wooden_axe')
    event.add('kubejs:banned_tools', 'minecraft:wooden_hoe')
    event.add('kubejs:banned_tools', 'minecraft:stone_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:stone_axe')
    event.add('kubejs:banned_tools', 'minecraft:stone_hoe')
    event.add('kubejs:banned_tools', 'minecraft:golden_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:golden_axe')
    event.add('kubejs:banned_tools', 'minecraft:golden_hoe')
    event.add('kubejs:banned_tools', 'minecraft:iron_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:iron_axe')
    event.add('kubejs:banned_tools', 'minecraft:iron_hoe')
    event.add('kubejs:banned_tools', 'minecraft:diamond_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:diamond_axe')
    event.add('kubejs:banned_tools', 'minecraft:diamond_hoe')
    event.add('kubejs:banned_tools', 'minecraft:netherite_pickaxe')
    event.add('kubejs:banned_tools', 'minecraft:netherite_axe')
    event.add('kubejs:banned_tools', 'minecraft:netherite_hoe')

    event.add('forge:tools/axes', 'appliedenergistics2:certus_quartz_axe')
    event.add('forge:tools/axes', 'appliedenergistics2:nether_quartz_axe')
    event.add('forge:tools/axes', 'astralsorcery:crystal_axe')
    event.add('forge:tools/axes', 'astralsorcery:infused_crystal_axe')
    event.add('forge:tools/axes', 'botania:manasteel_axe')
    event.add('forge:tools/axes', 'botania:elementium_axe')
    event.add('forge:tools/axes', 'projecte:dm_axe')
    event.add('forge:tools/axes', 'projecte:rm_axe')
    event.add('forge:tools/axes', 'tconstruct:hand_axe')
    event.add('forge:tools/axes', 'tconstruct:broad_axe')

    event.add('forge:tools/saws', 'thermal:flux_saw')
    
    event.add('kubejs:andesite_machine', 'create:mechanical_press')
    event.add('kubejs:andesite_machine', 'create:mechanical_mixer')
    event.add('kubejs:andesite_machine', 'create:speedometer')
    event.add('kubejs:andesite_machine', 'create:stressometer')
    event.add('kubejs:andesite_machine', 'create:mechanical_drill')
    event.add('kubejs:andesite_machine', 'create:mechanical_saw')
    event.add('kubejs:andesite_machine', 'create:deployer')
    event.add('kubejs:andesite_machine', 'create:mechanical_harvester')
    event.add('kubejs:andesite_machine', 'create:mechanical_plough')
    event.add('kubejs:andesite_machine', 'create:encased_fan')
    event.add('kubejs:andesite_machine', 'createaddition:rolling_mill')
    event.add('kubejs:andesite_machine', 'create:millstone')
    event.add('kubejs:andesite_machine', 'create:smart_chute')
    event.add('kubejs:andesite_machine', 'thermal:device_tree_extractor')
    event.add('kubejs:andesite_machine', 'thermal:device_fisher')
    event.add('kubejs:andesite_machine', 'mekanism:oredictionificator')

    event.add('kubejs:brass_machine', 'create:mechanical_crafter')
    event.add('kubejs:brass_machine', 'create:mechanical_arm')
    event.add('kubejs:brass_machine', 'create:sequenced_gearshift')
    event.add('kubejs:brass_machine', 'create:rotation_speed_controller')
    event.add('kubejs:brass_machine', 'create:portable_storage_interface')
    event.add('kubejs:brass_machine', 'create:content_observer')
    event.add('kubejs:brass_machine', 'create:stockpile_switch')
    event.add('kubejs:brass_machine', 'create:adjustable_crate')
    event.add('kubejs:brass_machine', 'create:nixie_tube')
    event.add('kubejs:brass_machine', 'thermal:device_hive_extractor')
    event.add('kubejs:brass_machine', 'thermal:device_rock_gen')
    event.add('kubejs:brass_machine', 'thermal:device_collector')
    event.add('kubejs:brass_machine', 'thermal:device_nullifier')
    event.add('kubejs:brass_machine', 'thermal:device_potion_diffuser')
    event.add('kubejs:brass_machine', 'tac:workbench')
    event.add('kubejs:brass_machine', 'vehicle:workstation')
    event.add('kubejs:brass_machine', 'tconstruct:scorched_alloyer')
    event.add('kubejs:brass_machine', 'tconstruct:foundry_controller')
    event.add('kubejs:brass_machine', 'tconstruct:smeltery_controller')

    event.add('kubejs:liquid_machine', 'thermal:device_water_gen')
    event.add('kubejs:liquid_machine', 'create:mechanical_pump')
    event.add('kubejs:liquid_machine', 'create:smart_fluid_pipe')
    event.add('kubejs:liquid_machine', 'create:fluid_valve')
    event.add('kubejs:liquid_machine', 'create:spout')
    event.add('kubejs:liquid_machine', 'create:hose_pulley')
    event.add('kubejs:liquid_machine', 'create:item_drain')
    event.add('kubejs:liquid_machine', 'create:portable_fluid_interface')
    event.add('kubejs:liquid_machine', 'thermal:fluid_cell')

    event.add('kubejs:steam_machine', 'steampowered:bronze_burner')
    event.add('kubejs:steam_machine', 'steampowered:cast_iron_burner')
    event.add('kubejs:steam_machine', 'steampowered:steel_burner')
    event.add('kubejs:steam_machine', 'steampowered:bronze_boiler')
    event.add('kubejs:steam_machine', 'steampowered:cast_iron_boiler')
    event.add('kubejs:steam_machine', 'steampowered:steel_boiler')
    event.add('kubejs:steam_machine', 'steampowered:bronze_steam_engine')
    event.add('kubejs:steam_machine', 'steampowered:cast_iron_steam_engine')
    event.add('kubejs:steam_machine', 'steampowered:steel_steam_engine')
    event.add('kubejs:steam_machine', 'steampowered:bronze_flywheel')
    event.add('kubejs:steam_machine', 'steampowered:cast_iron_flywheel')
    event.add('kubejs:steam_machine', 'steampowered:steel_flywheel')

    event.add('kubejs:electricity_machine', 'createaddition:electric_motor')
    event.add('kubejs:electricity_machine', 'createaddition:alternator')
    event.add('kubejs:electricity_machine', 'thermal:machine_frame')
    event.add('kubejs:electricity_machine', 'kubejs:flux_tool_casing')
    event.add('kubejs:electricity_machine', 'thermal:flux_drill')
    event.add('kubejs:electricity_machine', 'thermal:flux_saw')
    event.add('kubejs:electricity_machine', 'thermal:tinker_bench')
    event.add('kubejs:electricity_machine', 'thermal:charge_bench')
    event.add('kubejs:electricity_machine', 'extendedcrafting:frame')
    event.add('kubejs:electricity_machine', 'thermal:dynamo_stirling')
    event.add('kubejs:electricity_machine', 'thermal:dynamo_compression')
    event.add('kubejs:electricity_machine', 'thermal:dynamo_gourmand')
    event.add('kubejs:electricity_machine', 'thermal:dynamo_magmatic')
    event.add('kubejs:electricity_machine', 'thermal:energy_cell')
    event.add('kubejs:electricity_machine', 'thermal:machine_furnace')
    event.add('kubejs:electricity_machine', 'thermal:machine_smelter')
    event.add('kubejs:electricity_machine', 'thermal:machine_crucible')
    event.add('kubejs:electricity_machine', 'thermal:device_soil_infuser')
    event.add('kubejs:electricity_machine', 'thermal:machine_sawmill')
    event.add('kubejs:electricity_machine', 'thermal:machine_pulverizer')
    event.add('kubejs:electricity_machine', 'thermal:machine_press')
    event.add('kubejs:electricity_machine', 'thermal:machine_insolator')
    event.add('kubejs:electricity_machine', 'thermal:machine_centrifuge')
    event.add('kubejs:electricity_machine', 'thermal:machine_chiller')
    event.add('kubejs:electricity_machine', 'thermal:machine_refinery')
    event.add('kubejs:electricity_machine', 'thermal:machine_crafter')
    event.add('kubejs:electricity_machine', 'thermal:machine_brewer')
    event.add('kubejs:electricity_machine', 'thermal:machine_pyrolyzer')
    event.add('kubejs:electricity_machine', 'thermal:machine_bottler')
    event.add('kubejs:electricity_machine', 'ftb-power-pots:power_pot_mk1')
    event.add('kubejs:electricity_machine', 'ftb-power-pots:power_pot_mk2')
    event.add('kubejs:electricity_machine', 'ftb-power-pots:power_pot_mk3')
    event.add('kubejs:electricity_machine', 'ftb-power-pots:power_pot_mk4')
    event.add('kubejs:electricity_machine', 'extendedcrafting:crafting_core')

    event.add('kubejs:chromatic_machine', ['mekanism:enrichment_chamber', 'mekanism:osmium_compressor', 'mekanism:combiner', 'mekanism:crusher', 'mekanism:digital_miner', 'mekanism:metallurgic_infuser', 'mekanism:purification_chamber','mekanismgenerators:solar_generator', 'mekanismgenerators:heat_generator', 'mekanism:energized_smelter','mekanism:teleporter', 'mekanism:electric_pump', 'mekanism:chargepad',  'mekanism:rotary_condensentrator', 'mekanism:chemical_oxidizer', 'mekanism:chemical_infuser', 'mekanism:chemical_injection_chamber', 'mekanism:electrolytic_separator', 'mekanism:precision_sawmill', 'mekanism:chemical_dissolution_chamber', 'mekanism:chemical_washer', 'mekanism:chemical_crystallizer', 'mekanism:seismic_vibrator','mekanism:pressurized_reaction_chamber', 'mekanism:nutritional_liquifier', 'mekanism:fluidic_plenisher', 'mekanism:quantum_entangloporter', 'mekanism:resistive_heater','mekanism:fuelwood_heater', 'mekanism:pigment_extractor', 'mekanism:pigment_mixer', 'mekanism:painting_machine', 'mekanismgenerators:gas_burning_generator' ,'mekanismgenerators:bio_generator', 'mekanismgenerators:advanced_solar_generator', 'mekanismgenerators:wind_generator', 'mekanism:basic_energy_cube', 'mekanism:advanced_energy_cube', 'mekanism:elite_energy_cube', 'mekanism:ultimate_energy_cube', 'mekanism:modification_station', 'mekanism:antiprotonic_nucleosynthesizer', 'mekanism:solar_neutron_activator', 'mekanism:isotopic_centrifuge','mekanism:jetpack', 'mekanism:jetpack_armored', 'mekanism:flamethrower', 'mekanism:free_runners', 'mekanism:atomic_disassembler', 'mekanism:laser_amplifier', 'mekanism:laser', 'mekanism:formulaic_assemblicator'])

    event.add('kubejs:removed_recipes_machine', ['mekanism:portable_qio_dashboard', 'mekanism:qio_drive_base', 'mekanism:qio_drive_hyper_dense', 'mekanism:qio_drive_time_dilating', 'mekanism:qio_drive_supermassive', 'mekanism:qio_drive_array', 'mekanism:qio_dashboard', 'mekanism:qio_importer', 'mekanism:qio_exporter', 'mekanism:qio_redstone_adapter'])

    event.add('kubejs:restrict_mek', ['mekanism:robit', 'mekanism:energy_tablet', 'mekanism:configurator', 'mekanism:network_reader', 'mekanism:portable_teleporter', 'mekanism:configuration_card', 'mekanism:crafting_formula', 'mekanism:scuba_mask', 'mekanism:seismic_reader', 'mekanism:gauge_dropper', 'mekanism:geiger_counter', 'mekanism:dosimeter', 'mekanism:canteen', 'mekanism:atomic_disassembler', 'mekanism:electric_bow', 'mekanism:flamethrower', 'mekanism:free_runners', 'mekanism:scuba_tank' , 'mekanism:jetpack',  'mekanism:jetpack_armored', 'mekanism:hdpe_elytra' , 'mekanism:hazmat_mask', 'mekanism:hazmat_gown', 'mekanism:hazmat_pants', 'mekanism:hazmat_boots', 'mekanism:upgrade_speed', 'mekanism:upgrade_energy', 'mekanism:upgrade_filter', 'mekanism:upgrade_muffling', 'mekanism:upgrade_gas', 'mekanism:upgrade_anchor', 'mekanism:upgrade_stone_generator', 'mekanism:basic_tier_installer', 'mekanism:advanced_tier_installer', 'mekanism:elite_tier_installer', 'mekanism:ultimate_tier_installer', 'mekanism:basic_control_circuit', 'mekanism:advanced_control_circuit', 'mekanism:elite_control_circuit', 'mekanism:ultimate_control_circuit', 'mekanism:alloy_infused', 'mekanism:alloy_reinforced', 'mekanism:alloy_atomic', 'mekanism:enriched_carbon', 'mekanism:enriched_redstone', 'mekanism:enriched_diamond', 'mekanism:enriched_refined_obsidian', 'mekanism:enriched_gold', 'mekanism:enriched_tin', 'mekanism:hdpe_pellet', 'mekanism:hdpe_rod', 'mekanism:hdpe_sheet', 'mekanism:hdpe_stick', 'mekanism:electrolytic_core', 'mekanism:teleportation_core', 'mekanism:dust_diamond', 'mekanism:enriched_iron', 'mekanism:sawdust', 'mekanism:salt', 'mekanism:substrate', 'mekanism:bio_fuel', 'mekanism:dye_base', 'mekanism:yellow_cake_uranium', 'mekanism:dirty_netherite_scrap', 'mekanism:dust_bronze', 'mekanism:dust_lapis_lazuli', 'mekanism:dust_coal', 'mekanism:dust_charcoal', 'mekanism:dust_quartz', 'mekanism:dust_emerald', 'mekanism:dust_netherite', 'mekanism:dust_steel', 'mekanism:dust_sulfur', 'mekanism:dust_lithium', 'mekanism:dust_refined_obsidian', 'mekanism:dust_obsidian', 'mekanism:dust_fluorite', 'mekanism:dirty_dust_copper',  'mekanism:shard_iron', 'mekanism:shard_gold', 'mekanism:shard_osmium', 'mekanism:shard_copper', 'mekanism:shard_tin', 'mekanism:shard_lead', 'mekanism:shard_uranium', 'mekanism:crystal_iron', 'mekanism:crystal_gold', 'mekanism:crystal_osmium', 'mekanism:crystal_copper', 'mekanism:crystal_tin', 'mekanism:crystal_lead', 'mekanism:crystal_uranium', 'mekanism:dust_iron', 'mekanism:dust_gold', 'mekanism:dust_osmium', 'mekanism:dust_copper', 'mekanism:dust_tin', 'mekanism:dust_lead', 'mekanism:dust_uranium', 'mekanism:dirty_dust_iron', 'mekanism:dirty_dust_gold', 'mekanism:dirty_dust_osmium', 'mekanism:dirty_dust_tin', 'mekanism:dirty_dust_lead', 'mekanism:dirty_dust_uranium', 'mekanism:clump_iron', 'mekanism:clump_gold', 'mekanism:clump_osmium', 'mekanism:clump_copper', 'mekanism:clump_tin', 'mekanism:clump_lead', 'mekanism:clump_uranium', 'mekanism:steel_casing', 'mekanism:basic_bin', 'mekanism:advanced_bin', 'mekanism:elite_bin', 'mekanism:ultimate_bin', 'mekanism:dynamic_tank', 'mekanism:structural_glass', 'mekanism:dynamic_valve', 'mekanism:thermal_evaporation_controller', 'mekanism:thermal_evaporation_valve', 'mekanism:thermal_evaporation_block', 'mekanism:induction_casing', 'mekanism:induction_port', 'mekanism:basic_induction_cell', 'mekanism:advanced_induction_cell', 'mekanism:elite_induction_cell', 'mekanism:ultimate_induction_cell', 'mekanism:basic_induction_provider', 'mekanism:advanced_induction_provider', 'mekanism:elite_induction_provider', 'mekanism:ultimate_induction_provider', 'mekanism:superheating_element', 'mekanism:pressure_disperser', 'mekanism:boiler_casing', 'mekanism:boiler_valve', 'mekanism:security_desk', 'mekanism:industrial_alarm', 'mekanism:basic_fluid_tank', 'mekanism:advanced_fluid_tank', 'mekanism:elite_fluid_tank', 'mekanism:ultimate_fluid_tank', 'mekanism:basic_chemical_tank', 'mekanism:advanced_chemical_tank', 'mekanism:elite_chemical_tank', 'mekanism:ultimate_chemical_tank', 'mekanism:superheated_sodium_bucket', 'mekanism:brine_bucket', 'mekanism:hydrogen_bucket', 'mekanism:oxygen_bucket', 'mekanism:chlorine_bucket', 'mekanism:sulfur_dioxide_bucket', 'mekanism:sulfur_trioxide_bucket', 'mekanism:sulfuric_acid_bucket', 'mekanism:hydrogen_chloride_bucket', 'mekanism:hydrofluoric_acid_bucket', 'mekanism:uranium_oxide_bucket', 'mekanism:uranium_hexafluoride_bucket', 'mekanism:ethene_bucket', 'mekanism:sodium_bucket', 'mekanism:lithium_bucket', 'mekanism:steam_bucket', 'mekanism:heavy_water_bucket', 'mekanism:personal_chest', 'mekanism:logistical_sorter'])

    event.add('kubejs:meka_module', ['mekanism:module_base', 'mekanism:module_energy_unit', 'mekanism:module_laser_dissipation_unit', 'mekanism:module_radiation_shielding_unit', 'mekanism:module_excavation_escalation_unit', 'mekanism:module_attack_amplification_unit', 'mekanism:module_farming_unit', 'mekanism:module_shearing_unit', 'mekanism:module_silk_touch_unit', 'mekanism:module_vein_mining_unit', 'mekanism:module_teleportation_unit', 'mekanism:module_electrolytic_breathing_unit', 'mekanism:module_inhalation_purification_unit', 'mekanism:module_vision_enhancement_unit', 'mekanism:module_solar_recharging_unit', 'mekanism:module_nutritional_injection_unit', 'mekanism:module_dosimeter_unit', 'mekanism:module_geiger_unit', 'mekanism:module_jetpack_unit', 'mekanism:module_charge_distribution_unit', 'mekanism:module_gravitational_modulating_unit', 'mekanism:module_elytra_unit', 'mekanism:module_locomotive_boosting_unit', 'mekanism:module_hydraulic_propulsion_unit', 'mekanism:module_magnetic_attraction_unit', 'mekanism:module_frost_walker_unit'])

    event.add('kubejs:mek_factory', ['mekanism:basic_smelting_factory', 'mekanism:basic_enriching_factory', 'mekanism:basic_crushing_factory', 'mekanism:basic_compressing_factory', 'mekanism:basic_combining_factory', 'mekanism:basic_purifying_factory', 'mekanism:basic_injecting_factory', 'mekanism:basic_infusing_factory', 'mekanism:basic_sawing_factory', 'mekanism:advanced_smelting_factory', 'mekanism:advanced_enriching_factory', 'mekanism:advanced_crushing_factory', 'mekanism:advanced_compressing_factory', 'mekanism:advanced_combining_factory', 'mekanism:advanced_purifying_factory', 'mekanism:advanced_injecting_factory', 'mekanism:advanced_infusing_factory', 'mekanism:advanced_sawing_factory', 'mekanism:elite_smelting_factory', 'mekanism:elite_enriching_factory', 'mekanism:elite_crushing_factory', 'mekanism:elite_compressing_factory', 'mekanism:elite_combining_factory', 'mekanism:elite_purifying_factory', 'mekanism:elite_injecting_factory', 'mekanism:elite_infusing_factory', 'mekanism:elite_sawing_factory', 'mekanism:ultimate_smelting_factory', 'mekanism:ultimate_enriching_factory', 'mekanism:ultimate_crushing_factory', 'mekanism:ultimate_compressing_factory', 'mekanism:ultimate_combining_factory', 'mekanism:ultimate_purifying_factory', 'mekanism:ultimate_injecting_factory', 'mekanism:ultimate_infusing_factory', 'mekanism:ultimate_sawing_factory'])

    event.add('forge:ingots', ['create:andesite_alloy', 'kubejs:blaze_brass', 'kubejs:chorus_chrome', "kubejs:antimatter_alloy"])
    event.add('forge:storage_blocks/refined_radiance', 'kubejs:refined_radiance_block')
    event.add('forge:storage_blocks/shadow_steel', 'kubejs:shadow_steel_block')
    event.add('kubejs:shifting_stars', ['astralsorcery:shifting_star_aevitas', 'astralsorcery:shifting_star_armara', 'astralsorcery:shifting_star_discidia', 'astralsorcery:shifting_star_evorsio', 'astralsorcery:shifting_star_vicio'])

    event.add('kubejs:disabled', ['mysticalagradditions:tertium_paxel', 'mysticalagradditions:imperium_paxel','mysticalagradditions:supremium_paxel', 'mysticalagriculture:inferium_sword', 'mysticalagriculture:inferium_pickaxe', 'mysticalagriculture:inferium_shovel', 'mysticalagriculture:inferium_axe', 'mysticalagriculture:inferium_hoe', 'mysticalagriculture:prudentium_sword', 'mysticalagriculture:prudentium_pickaxe', 'mysticalagriculture:prudentium_shovel', 'mysticalagriculture:prudentium_axe', 'mysticalagriculture:prudentium_hoe', 'mysticalagriculture:tertium_sword', 'mysticalagriculture:tertium_pickaxe', 'mysticalagriculture:tertium_shovel', 'mysticalagriculture:tertium_axe', 'mysticalagriculture:tertium_hoe', 'mysticalagriculture:imperium_sword', 'mysticalagriculture:imperium_pickaxe', 'mysticalagriculture:imperium_shovel', 'mysticalagriculture:imperium_axe', 'mysticalagriculture:imperium_hoe', 'mysticalagriculture:supremium_sword', 'mysticalagriculture:supremium_pickaxe', 'mysticalagriculture:supremium_shovel', 'mysticalagriculture:supremium_axe', 'mysticalagriculture:supremium_hoe', 'mysticalagradditions:inferium_paxel', 'mysticalagradditions:prudentium_paxel'])
    event.add('kubejs:disabled', ['projecte:alchemical_chest', 'projecte:dm_pedestal', '#projecte:alchemical_bags', 'projecte:dm_helmet', 'projecte:dm_chestplate', 'projecte:dm_leggings', 'projecte:dm_boots', 'projecte:rm_helmet', 'projecte:rm_chestplate', 'projecte:rm_leggings', 'projecte:rm_boots', 'projecte:iron_band', 'projecte:gem_of_eternal_density', 'projecte:mercurial_eye', 'projecte:body_stone', 'projecte:soul_stone', 'projecte:mind_stone', 'projecte:life_stone', 'projecte:destruction_catalyst', 'projecte:hyperkinetic_lens', 'projecte:catalytic_lens', 'projecte:rm_katar', 'projecte:rm_morning_star', 'projecte:void_ring', 'projecte:arcana_ring', 'projecte:gem_helmet', 'projecte:gem_chestplate', 'projecte:gem_leggings', 'projecte:gem_boots', 'projecte:rm_hammer', 'projecte:dm_hammer', 'projecte:dm_shears', 'projecte:dm_hoe', 'projecte:dm_shovel', 'projecte:dm_axe', 'projecte:dm_sword', 'projecte:rm_hammer', 'projecte:rm_shears', 'projecte:rm_hoe', 'projecte:rm_sword', 'projecte:rm_shovel', 'projecte:rm_axe', 'projecte:archangel_smite', 'projecte:black_hole_band', 'projecte:ignition_ring', 'projecte:harvest_goddess_band', 'projecte:swiftwolf_rending_gale', 'projecte:zero_ring'])
})
onEvent('block.tags', event => {
    event.add('notreepunching:always_breakable', 'minecraft:snow')
})