
# Options related to enabling/disabling specific features
# See the jsons folder to customize the temperature of specific blocks, liquids, armors, etc.
# To reload your JSONs, type /reload into chat with cheats enabled; The same way you reload datapacks, crafttweaker scripts, etc.
[core]
	# Whether or not the temperature system is enabled.
	"Temperature Enabled" = true
	# Whether or not heart fruits are functional and generate in-world.
	"Heart Fruits Enabled" = true

	[core.advanced]
		# How often player temperature is regularly synced between the client and server, in ticks.
		# Lower values will increase accuracy at the cost of performance
		#Range: > 1
		"Routine Packet Sync" = 30

# Options related to the temperature system
[temperature]
	# Currently non-functional.
	"Dangerous Temperature Effects" = true
	# Currently non-functional.
	"Secondary Temperature Effects" = true
	# How much of an effect being on fire has on a player's temperature.
	"Player On Fire Modifier" = 12.5
	# How much of an effect sprinting has on a player's temperature.
	"Player Sprint Modifier" = 1.5
	# Increases/decreases the effect that cooling/heating enchantments have on a player's temperature.
	"Enchantment Modifier" = 1.0

	[temperature.wetness]
		# How a player's "wetness" is determined. Accepted values are as follows:
		#   DISABLE - Disable wetness and any effects on temperature it might have.
		#   SIMPLE - Wetness is only based on whether you're in water/rain or not. Slightly better in terms of performance.
		#   DYNAMIC - Wetness can change dynamically based on various conditions, and does not instantly go away when moving out of water.
		# Any other value will default to DISABLE.
		"Wetness Mode" = "DYNAMIC"
		# How much being wet influences the player's temperature.
		"Wetness Modifier" = -7.0

	[temperature.huddling]
		# How much nearby players increase the ambient temperature by.
		# Note that this value stacks!
		"Player Huddling Modifier" = 0.5
		# The radius, in blocks, around which players will add to each other's temperature.
		#Range: 0 ~ 10
		"Player Huddling Radius" = 1

	[temperature.environment]
		# How much the effects of the player's altitude on temperature are multiplied.
		"Altitude Modifier" = 3.0

		[temperature.environment.biomes]
			# How much a biome's temperature effects are multiplied.
			#Range: 0.0 ~ Infinity
			"Biome Temperature Multiplier" = 16.0
			# Whether or not biomes will have an effect on a player's temperature.
			"Biomes affect Temperature" = true

		[temperature.environment.weather]
			# How much of an effect rain has on temperature.
			"Rain Temperature Modifier" = -2.0
			# How much of an effect snow has on temperature.
			"Snow Temperature Modifier" = -6.0

		[temperature.environment.time]
			# Staying in the shade will reduce a player's temperature by this amount.
			# Only effective in hot biomes!
			"Time Shade Modifier" = -3

			[temperature.environment.time.multipliers]
				# How strongly the effects of time on temperature are multiplied.
				#Range: 0.0 ~ Infinity
				"Time Multiplier" = 2.0
				# How strongly different biomes affect temperature, based on time.
				#Range: 1.0 ~ Infinity
				"Biome Time Multiplier" = 1.75

	[temperature.advanced]
		# Maximum horizontal distance, in blocks, where heat sources will have an effect on temperature.
		#Range: 1 ~ 10
		"Temperature Influence Horizontal Distance" = 3
		# Maximum vertical distance, in blocks, where heat sources will have an effect on temperature.
		#Range: 1 ~ 10
		"Temperature Influence Vertical Distance" = 2

		[temperature.advanced.tickrate]
			# Maximum amount of time between temperature ticks.
			#Range: > 20
			"Maximum Temperature Tickrate" = 200
			# Minimum amount of time between temperature ticks.
			#Range: > 20
			"Minimum Temperature Tickrate" = 20

	[temperature.compat]

		[temperature.compat.seasons]
			# If Serene Seasons is installed, then seasons
			# will have an effect on the player's temperature.
			"Seasons affect Temperature" = true

			#Temperature modifiers per season in temperate biomes.
			[temperature.compat.seasons.temperate]

				[temperature.compat.seasons.temperate.spring]
					"Early Spring Modifier" = -3
					"Mid Spring Modifier" = 0
					"Late Spring Modifier" = 3

				[temperature.compat.seasons.temperate.summer]
					"Early Summer Modifier" = 5
					"Mid Summer Modifier" = 8
					"Late Summer Modifier" = 5

				[temperature.compat.seasons.temperate.autumn]
					"Early Autumn Modifier" = 3
					"Mid Autumn Modifier" = 0
					"Late Autumn Modifier" = -3

				[temperature.compat.seasons.temperate.winter]
					"Early Winter Modifier" = -7
					"Mid Winter Modifier" = -12
					"Late Winter Modifier" = -7

			#Temperature modifiers per season in tropical biomes.
			[temperature.compat.seasons.tropical]

				[temperature.compat.seasons.tropical.wet-season]
					"Early Wet Season Modifier" = -1
					"Mid Wet Season Modifier" = -5
					"Late Wet Season Modifier" = -1

				[temperature.compat.seasons.tropical.dry-season]
					"Early Dry Season Modifier" = 3
					"Mid Dry Season Modifier" = 7
					"Late Dry Season Modifier" = 3

	# Options relating to heart fruits
	[temperature.heart-fruits]
		# Maximum number of additional hearts that can be given by Heart Fruits.
		#Range: > 1
		"Maximum Additional Hearts" = 100
		# The number of additional hearts lost on death.
		# Set to -1 to force loss of all additional hearts on death.
		# Set to 0 to make additional hearts permanent.
		#Range: > -1
		"Hearts Lost On Death" = 0

		[temperature.heart-fruits.effects]
			# Amount of hearts gained from eating a Heart Fruit.
			#Range: > 1
			"Additional Hearts Per Heart Fruit" = 1
			# Whether or not Heart Fruits give a strong regeneration effect.
			"Heart Fruits Give Regen" = true

