// priority: 0 

settings.logAddedRecipes = false
settings.logRemovedRecipes = false
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

onEvent('recipes', event => {
    event.remove({mod: 'zombie_extreme'})

    event.remove({id: 'notreepunching:flint_pickaxe'})
    event.remove({id: 'notreepunching:flint_hoe'})
    event.remove({output: '#forge:tools/mattocks'})
    event.remove({id: 'tconstruct:common/flint'})
    event.remove({id: 'croptopia:steamed_rice'})
    event.remove({id: 'minecraft:bread'})
    event.remove({id: 'appliedenergistics2:grinder/flour'})
    event.remove({input: 'appliedenergistics2:flour'})
    event.remove({output: 'create:dough'})
    event.remove({input: 'create:dough'})
    event.remove({output: 'farmersdelight:wheat_dough'})
    event.remove({id: 'croptopia:knife'})
    event.remove({id: 'thermal:rubber_from_vine'})
    event.remove({id: 'thermal:rubber_3'})
    event.remove({id: 'thermal:rubber_from_dandelion'})
    event.remove({id: 'extendedcrafting:ender_crafter'})
    event.remove({id: 'extendedcrafting:ender_alternator'})
    event.remove({output: '#inventorypets:all_pets'})
    event.remove({input: 'charm:netherite_nugget'})
    event.remove({output: 'charm:netherite_nugget'})
    event.remove({output: 'create:precision_mechanism'})
    event.remove({output: 'create:andesite_alloy'})
    event.remove({output: 'create:cogwheel'})
    event.remove({output: 'create:large_cogwheel'})
    event.remove({output: 'minecraft:ender_eye'})
    event.remove({id: 'miniutilities:unstable_ingot'})
    event.remove({id: 'vehicle:fluid_mixer'})
    event.remove({id: 'vehicle:fluid_extracter'})
    event.remove({id: 'thermal:saw_blade'})
    event.remove({id: 'thermal:drill_head'})
    event.remove({type: 'immersiveengineering:alloy'})
    event.remove({id: 'thermal:fire_charge/bronze_ingot_4'})
    event.remove({id: 'thermal:bronze_dust_4'})
    event.remove({id: 'immersiveengineering:crafting/blastbrick'})
    event.remove({id: 'immersiveengineering:crafting/cokebrick'})
    event.remove({id: 'thermal:fire_charge/electrum_ingot_2'})
    event.remove({id: 'thermal:electrum_dust_2'})
    event.remove({id: 'thermal:fire_charge/invar_ingot_3'})
    event.remove({id: 'thermal:invar_dust_3'})
    event.remove({id: 'thermal:fire_charge/constantan_ingot_2'})
    event.remove({id: 'thermal:constantan_dust_2'})
    event.remove({id: 'thermal:chiller_ball_cast'})
    event.remove({id: 'thermal:chiller_ingot_cast'})
    event.remove({id: 'thermal:chiller_rod_cast'})
    event.remove({id: 'create:crafting/materials/rose_quartz'})
    event.remove({id: 'scalinghealth:heart_crystal'})
    event.remove({id: 'scalinghealth:power_crystal'})
    event.remove({output: ['botania:apothecary_default', 'botania:fertilizer']})
    event.remove({output: 'astralsorcery:wand'})
    event.remove({output: ['bloodmagic:altar', 'bloodmagic:soulforge', 'bloodmagic:alchemytable', 'bloodmagic:incensealtar', 'bloodmagic:sacrificialdagger', 'bloodmagic:alchemicalreactionchamber']})
    event.remove({input: 'mahoutsukai:hammer'})
    event.remove({id: 'mahoutsukai:hammer'})
    event.remove({id: 'create:crafting/materials/andesite_casing'})
    event.remove({id: 'create:crafting/materials/brass_casing'})
    event.remove({id: 'create:crafting/materials/copper_casing'})
    event.remove({id: 'create:crafting/materials/refined_radiance_casing'})
    event.remove({id: 'create:crafting/materials/shadow_steel_casing'})
    event.remove({id: 'createaddition:crafting/overcharged_casing'})
    event.remove({id: 'projecte:dm_furnace'})
    event.remove({id: 'ironfurnaces:heater'})
    event.remove({id: 'ironfurnaces:item_heater'})
    event.remove({id: 'minecraft:torch'})
    event.remove({id: 'pipez:item_pipe'})
    event.remove({id: 'pipez:fluid_pipe'})
    event.remove({id: 'pipez:energy_pipe'})
    event.remove({id: 'pipez:gas_pipe'})
    event.remove({id: 'pipez:universal_pipe'})
    event.remove({id: 'tiab:timeinabottle'})
    event.remove({id: 'vehicle:small_engine_wood'})
    event.remove({id: 'vehicle:large_engine_wood'})
    event.remove({id: 'vehicle:electric_engine_wood'})
    event.remove({id: 'mekanism:dictionary'})
    event.remove({output: '#kubejs:andesite_machine'})
    event.remove({output: '#kubejs:brass_machine'})
    event.remove({output: '#kubejs:liquid_machine'})
    event.remove({id: 'steampowered:bronze_cogwheel'})
    event.remove({id: 'steampowered:bronze_large_cogwheel'})
    event.remove({id: 'steampowered:cast_iron_cogwheel'})
    event.remove({id: 'steampowered:cast_iron_large_cogwheel'})
    event.remove({id: 'steampowered:steel_cogwheel'})
    event.remove({id: 'steampowered:steel_large_cogwheel'})
    event.remove({output: '#kubejs:steam_machine'})

    event.remove({id: 'createaddition:rolling/copper_plate'})
    event.remove({id: 'immersiveengineering:crafting/wire_copper'})
    event.remove({id: 'immersiveengineering:crafting/wire_lead'})
    event.remove({id: 'immersiveengineering:crafting/wire_aluminum'})
    event.remove({id: 'immersiveengineering:crafting/wire_electrum'})
    event.remove({id: 'immersiveengineering:crafting/wire_steel'})
    event.remove({id: 'immersiveengineering:crafting/plate_iron_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_silver_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_aluminum_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_gold_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_steel_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_electrum_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_uranium_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_copper_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_nickel_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_lead_hammering'})
    event.remove({id: 'immersiveengineering:crafting/plate_constantan_hammering'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_osmium'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_nickel'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_lead'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_silver'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_uranium'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_tin'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_iron'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_gold'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_copper'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_aluminum'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_zinc'})
    event.remove({id: 'immersiveengineering:crafting/hammercrushing_cobalt'})
    event.remove({id: 'createaddition:crafting/heater'})
    event.remove({id: 'createaddition:crafting/tesla_coil'})
    event.remove({id: 'createaddition:compat/immersiveengineering/constantan'})
    event.remove({id: 'createaddition:compat/immersiveengineering/electrum'})
    event.remove({id: 'createaddition:mechanical_crafting/motor'})
    event.remove({id: 'createaddition:mechanical_crafting/alternator'})
    event.remove({id: 'immersiveengineering:crafting/constantan_mix'})
    event.remove({id: 'immersiveengineering:crafting/electrum_mix'})
    event.remove({id: 'immersiveengineering:crafting/component_iron'})
    event.remove({id: 'immersiveengineering:crafting/component_steel'})
    event.remove({id: 'thermal:fire_charge/signalum_ingot_4'})
    event.remove({id: 'thermal:signalum_dust_4'})
    event.remove({id: 'thermal:lumium_dust_4'})
    event.remove({id: 'thermal:fire_charge/lumium_ingot_4'})
    event.remove({id: 'thermal:machine/smelter/smelter_alloy_lumium'})
    event.remove({id: 'tconstruct:smeltery/alloys/molten_lumium'})
    event.remove({id: 'extendedcrafting:luminessence'})
    event.remove({id: 'thermal:enderium_dust_2'})
    event.remove({id: 'thermal:fire_charge/enderium_ingot_2'})
    event.remove({id: 'thermal:machine/smelter/smelter_alloy_enderium'})
    event.remove({id: 'tconstruct:smeltery/alloys/molten_enderium'})
    event.remove({id: 'extendedcrafting:ender_ingot'})
    event.remove({output: ['rftoolsbase:machine_frame','woot:machine_casing']})

    event.remove({output: ['immersiveengineering:capacitor_lv', 'immersiveengineering:capacitor_mv', 'immersiveengineering:capacitor_hv', 'immersiveengineering:thermoelectric_generator', 'extendedcrafting:crafting_core', 'thermal:machine_frame']})

    event.remove({id: 'rftoolsbase:dimensionalshard'})
    event.remove({id: 'create:mixing/chromatic_compound'})

    event.remove({output: 'botania:runic_altar'})

    event.remove({output: 'mekanism:basic_energy_cube'})
    event.remove({output: 'mekanism:steel_casing'})
    event.remove({id: 'mekanism:metallurgic_infusing/alloy/infused'})
    event.remove({id: 'mekanism:control_circuit/basic'})
    event.remove({id: 'mekanism:control_circuit/advanced'})
    event.remove({id: 'mekanism:control_circuit/elite'})
    event.remove({id: 'mekanism:control_circuit/ultimate'})
    event.remove({id: 'mekanism:teleportation_core'})
    event.remove({id: 'mekanism:mekasuit_helmet'})
    event.remove({id: 'mekanism:mekasuit_bodyarmor'})
    event.remove({id: 'mekanism:mekasuit_pants'})
    event.remove({id: 'mekanism:mekasuit_boots'})
    event.remove({id: 'mekanism:meka_tool'})
    event.remove({id: 'compactvoidminers:void_miner'})
    event.remove({id: 'mekanism:induction/cell/basic'})
    event.remove({id: 'mekanism:induction/cell/advanced'})
    event.remove({id: 'mekanism:induction/cell/elite'})
    event.remove({id: 'mekanism:induction/cell/ultimate'})
    event.remove({id: 'mekanism:induction/provider/basic'})
    event.remove({id: 'mekanism:induction/provider/advanced'})
    event.remove({id: 'mekanism:induction/provider/elite'})
    event.remove({id: 'mekanism:induction/provider/ultimate'})

    event.remove({id: 'endless:extreme_crafting_table'})
    event.remove({id: 'endless:diamond_lattice'})
    event.remove({id: 'endless:crystal_matrix_ingot'})
    event.remove({output: ['projecte:condenser_mk1', 'projecte:collector_mk1', 'projecte:relay_mk1']})
    event.remove({id: 'projecte:dark_matter'})
    event.remove({id: 'projecte:red_matter'})
    event.remove({id: 'projecte:red_matter_alt'})
    event.remove({id: 'projecte:philosophers_stone'})
    event.remove({id: 'projecte:philosophers_stone_alt'})
    event.remove({id: 'projecte:transmutation_table'})
    event.remove({id: 'projecte:transmutation_tablet'})
    event.remove({id: 'projecte:evertide_amulet'})
    event.remove({id: 'projecte:volcanite_amulet'})
    event.remove({id: 'projecte:watch_of_flowing_time'})
    event.remove({output: 'projecte:repair_talisman'})
    event.remove({id: 'endless:sd_creative_vending_upgrade'})
    event.remove({id: 'endless:ae2_creative_energy_cell'})
    event.remove({id: 'endless:sd_creative_storage_upgrade'})
    event.remove({id: 'endless:tc3_creative_slot_upgrades'})
    event.remove({id: 'endless:tc3_creative_slot_abilities'})
    event.remove({id: 'endless:tc3_creative_slot_souls'})
    event.remove({id: 'endless:tc3_creative_slot_defense'})
    event.remove({id: 'endless:bot_creative_pool'})
    event.remove({id: 'endless:bot_creative_mana_tablet'})
    
    event.remove({output: '#kubejs:disabled'})
})