onEvent('block.registry', event => {
    event.create('andesite_alloy_block', block => {
          block.material('iron')
        block.hardness(6)
        block.displayName('安山合金块')
        block.requiresTool(true)
        block.resistance(6)
        block.harvestTool('pickaxe', 1)
    })
    event.create('rose_quartz_block', block => {
        block.material('iron')
      block.hardness(6)
      block.displayName('玫瑰石英块')
      block.requiresTool(true)
      block.resistance(6)
      block.harvestTool('pickaxe', 1)
    })
    event.create('chromatic_compound_block', block => {
        block.material('iron')
      block.hardness(10)
      block.displayName('§e异彩化合物块')
      block.requiresTool(true)
      block.resistance(10)
      block.harvestTool('pickaxe', 3)
      block.lightLevel(0.5)
    })
    event.create('shadow_steel_block', block => {
        block.material('iron')
      block.hardness(10)
      block.displayName('§e暗影钢块')
      block.requiresTool(true)
      block.resistance(10)
      block.harvestTool('pickaxe', 3)
      block.lightLevel(0.25)
    })
    event.create('refined_radiance_block', block => {
        block.material('iron')
      block.hardness(10)
      block.displayName('§e光辉石块')
      block.requiresTool(true)
      block.resistance(10)
      block.harvestTool('pickaxe', 3)
      block.lightLevel(1)
  })
  event.create('overcharged_alloy_block', block => {
        block.material('iron')
      block.hardness(10)
      block.displayName('§e超负荷合金块')
      block.requiresTool(true)
      block.resistance(10)
      block.harvestTool('pickaxe', 3)
      block.lightLevel(0.8)
  })
  event.create('blaze_brass_block', block => {
      block.material('iron')
    block.hardness(8)
    block.displayName('§e烈焰合金块')
    block.requiresTool(true)
    block.resistance(8)
    block.harvestTool('pickaxe', 2)
    block.lightLevel(1)
  })
  event.create('chorus_chrome_block', block => {
      block.material('iron')
    block.hardness(8)
    block.displayName('§e紫颂合金块')
    block.requiresTool(true)
    block.resistance(8)
    block.harvestTool('pickaxe', 2)
    block.lightLevel(0.5)
  })
  event.create('ice_brass_block', block => {
      block.material('iron')
    block.hardness(8)
    block.displayName('§e凛冰合金块')
    block.requiresTool(true)
    block.resistance(8)
    block.harvestTool('pickaxe', 2)
    block.lightLevel(1)
  })
  event.create('hollow_alloy_block', block => {
      block.material('iron')
    block.hardness(8)
    block.displayName('§e中空合金块')
    block.requiresTool(true)
    block.resistance(8)
    block.harvestTool('pickaxe', 2)
    block.lightLevel(0.5)
  })
  event.create('gaia_block', block => {
      block.material('iron')
    block.hardness(8)
    block.displayName('盖亚魂块')
    block.requiresTool(true)
    block.resistance(8)
    block.harvestTool('pickaxe', 2)
    block.lightLevel(0.2)
  })
  event.create('antimatter_alloy_block', block => {
      block.material('iron')
    block.hardness(12)
    block.displayName('§e反物质合金块')
    block.requiresTool(true)
    block.resistance(20)
    block.harvestTool('pickaxe', 5)
    block.lightLevel(1)
  })
})