onEvent('fluid.registry', event => {
    event.create("chorus_solution")
        .textureThick(0x9319ca)
        .displayName("紫颂溶液")
        .bucketColor(0x9319ca)
    event.create("lumium_solution")
        .textureThick(0xF3FF00)
        .displayName("流明精华溶液")
        .bucketColor(0xF3FF00)
    event.create("cold_ice")
        .textureThin(0xBBFFFD)
        .displayName("凛冰")
        .bucketColor(0xBBFFFD)
})