
[gui]
	#The x-position of the GUI button
	#Range: -10000 ~ 10000
	buttonX = 20
	#The y-position of the GUI button
	#Range: -10000 ~ 10000
	buttonY = -20
	#True to add the Diet button to the inventory GUI, false otherwise
	addButton = true
	#The main text color for the GUI
	textColor = "4210752"

