
#General settings
[general]
	#Set memory sweep time.The unit is minutes.If the value is 0, it will be disabled.
	#Range: > 0
	"memory sweep time" = 15
	#Cleaner memory according to the memory usage of the JVM.If the value is 0 or 100, it will be disabled.
	#Clean the memory according to the memory usage rate at most once every 2 minutes.
	#If triggered frequently, it is still recommended to increase RAM or allocate more RAM.
	#Range: 0 ~ 100
	"memory usage" = 90
	#Time between memory cleanups based on memory usage.
	#Please do not make it larger than memory sweep time
	#Range: > 2
	"memory usage time" = 4
	#Clean memory when players join the world.
	#Only the first player is valid.
	"player join world sweep" = true
	#Control command send text.
	"command test" = true
	#Control automatic memory cleaner send text.
	"automatic memory cleaner test" = true

