
[general]
	rightClickToEdit = false
	menuAnimation = true
	toggle = false
	releaseToSelect = false
	menuButtonIcon = "minecraft:stone"

[visual]

	[visual.select]
		#Range: 0 ~ 255
		red = 255
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0
		#Range: 0 ~ 255
		alpha = 153

	[visual.menu]
		#Range: 0 ~ 255
		red = 0
		#Range: 0 ~ 255
		green = 0
		#Range: 0 ~ 255
		blue = 0
		#Range: 0 ~ 255
		alpha = 153

