#These JEI plugins will be loaded on the main thread
blacklist_async_jei_plugins = ["jepb:jei_plugin"]
#Thread priority to use for the integrated server. By default this is one less than the client thread, to help prevent the server from lowering FPS.
#Range: 1 ~ 10
integratedServerPriority = 4
#Priority to use for the background workers that complete various tasks. By default this is one less than the client thread.
#Range: 1 ~ 10
backgroundWorkerPriority = 4

